Fix regression branch
su2code/SU2 pull request #1817
Opened 2022-11-10 20:22 UTC by WallyMaier

## Proposed Changes
A recent change from #1417, which I merged in had the regression set to feature_cat_wall  in the TestCases. This will update and fix that call.  I'm sure I will need to check additional fixes associated with this change.

2022-11-10 22:33 UTC, pcarruscag requested changes
Ok wait. @bigfooted also merged something to testcases with new restarts for the work in axisymmetry fix.

2022-11-10 23:07 UTC, WallyMaier commented
@pcarruscag @bigfooted I can see the changes. It looks like a restart filename changed.  But I can hold off on fixing the regression value and merging the changes.

2022-11-11 00:41 UTC, pcarruscag approved these changes

2022-11-11 00:41 UTC, pcarruscag commented on .github/workflows/regression.yml
> +          args: -b ${{github.ref}} -t develop -c develop_tmp -s ${{matrix.testscript}}
Update what you need to update but do not change this branch to develop for now

2022-11-11 04:56 UTC, merged

2022-11-11 15:55 UTC, WallyMaier commented
@pcarruscag I saw this got merged.  What do you think the next steps are with develop_tmp?

2022-11-11 16:01 UTC, pcarruscag commented
We remove it after #1784 is merged